info:
  title: "zkDatabase API Documentation"
  description: "This is the documentation for zkDatabase API."
  version: "1.0.0"

introspection:
  url: "http://zkdb-serverless.zenfactory.org/graphql"

output:
  directory: "./docs"

theme:
  logo:
    url: "https://avatars.githubusercontent.com/u/94106298?s=200&v=4"
