name: 'Build & Push Selected Docker Images to Docker Hub'

on:
  push:
    branches:
      - main
      - devops/test-ci-cd
jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      filtered_packages: ${{ steps.filter.outputs.filtered_packages }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full commit history

      - name: Detect last two merge commits and diff
        id: changed
        run: |
          LAST_MERGE=$(git log --merges --pretty=format:'%H' -n 10)
          MERGE_ARRAY=($LAST_MERGE)
          LAST_MERGE_COMMIT=${MERGE_ARRAY[0]}
          PREV_MERGE_COMMIT=${MERGE_ARRAY[9]}
          
          echo "Last merge commit: $LAST_MERGE_COMMIT"
          echo "Previous merge commit: $PREV_MERGE_COMMIT"
          
          CHANGED_PACKAGES=$(git diff --name-only $PREV_MERGE_COMMIT $LAST_MERGE_COMMIT -- packages/ | cut -d '/' -f 1-2 | sort -u)
          CLEANED_PACKAGES=$(echo "$CHANGED_PACKAGES" | tr -d '\r' | tr '\n' ' ')
          echo "Cleaned packages: $CLEANED_PACKAGES"
          echo "changed_packages=$CLEANED_PACKAGES" >> $GITHUB_ENV

      - name: Filter packages using case statement and map to numbers
        id: filter
        run: |
          CHANGED_PACKAGES="${{ env.changed_packages }}"
          echo "Changed packages: $CHANGED_PACKAGES"
          FILTERED_PACKAGES=""
          declare -A PACKAGE_MAP
          PACKAGE_MAP["packages/serverless"]=1
          PACKAGE_MAP["packages/broker-service"]=2
          PACKAGE_MAP["packages/proof-service"]=3
          PACKAGE_MAP["packages/ftp"]=4

          IFS=' ' read -r -a PACKAGE_ARRAY <<< "$CHANGED_PACKAGES"
          for PACKAGE in "${PACKAGE_ARRAY[@]}"; do
            case $PACKAGE in
              "packages/serverless") FILTERED_PACKAGES="$FILTERED_PACKAGES 1" ;;
              "packages/broker-service") FILTERED_PACKAGES="$FILTERED_PACKAGES 2" ;;
              "packages/proof-service") FILTERED_PACKAGES="$FILTERED_PACKAGES 3" ;;
              "packages/ftp") FILTERED_PACKAGES="$FILTERED_PACKAGES 4" ;;
            esac
          done

          FILTERED_PACKAGES=$(echo $FILTERED_PACKAGES | xargs)
          echo "Filtered packages: ${FILTERED_PACKAGES[@]}"
          echo "filtered_packages=$FILTERED_PACKAGES" >> $GITHUB_OUTPUT

  build:
    name: Build & Push Docker Images and Push to GitOps
    needs: detect-changes
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.build.outputs.changed_services }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & Push Docker Images
        id: build
        run: |
          SERVICES=("serverless" "broker" "proof" "ftp")
          DOCKER_REPOS=(
            "orochinetwork/zkdb-serverless"
            "orochinetwork/zkdb-broker-service"
            "orochinetwork/zkdb-proof-service"
            "orochinetwork/zkdb-ftp"
          )
          CHANGED_SERVICES=""
          for i in ${!SERVICES[@]}; do
            SERVICE="${SERVICES[$i]}"
            DOCKER_REPO="${DOCKER_REPOS[$i]}"
            NUM=$((i + 1))
            if [[ -n "$DOCKER_REPO" && "${{ needs.detect-changes.outputs.filtered_packages }}" == *"$NUM"* ]]; then
              echo "Building and pushing $SERVICE..."
              CHANGED_SERVICES="$CHANGED_SERVICES $SERVICE"
            else
              echo "$SERVICE not changed or invalid Docker repo, skipping."
            fi
          done
          echo "::set-output name=changed_services::$CHANGED_SERVICES"

  gitops-push:
    name: Push Changes to GitOps
    needs: build
    runs-on: ubuntu-latest
    env:
      version: ${{ github.sha }}
      gitopsbranch: devops/test-gitops
    steps:
      - name: Set up SSH
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git config --global user.name "GitOps Updater"
          git config --global user.email "minhan112001@gmail.com"
          git clone git@github.com:ZKP-Labs/test-argoCD.git

          cd test-argoCD
          git checkout ${{ env.gitopsbranch }}
          IFS=' ' read -r -a CHANGED_SERVICES_ARRAY <<< "${{ needs.build.outputs.changed_services }}"
          CHANGED_SERVICES=$(IFS=,; echo "${CHANGED_SERVICES_ARRAY[*]}")
          echo "Changed services: $CHANGED_SERVICES"
          for SERVICE in "${CHANGED_SERVICES_ARRAY[@]}"; do
            VALUES_PATH="services/orochi/zkDatabase/$SERVICE/zkdb-$SERVICE/values.yaml"
            sed -i "s| tag: .*| tag: "latesttt"|" "$VALUES_PATH"
            git add "$VALUES_PATH"
          done

          echo "Committing and pushing changes for ${CHANGED_SERVICES} to ${{ env.gitopsbranch }} version ${{ env.version }}"
          git commit -m "Update versions for: ${CHANGED_SERVICES} to ${{ env.version }}"
          git push origin ${{ env.gitopsbranch }}
